#!/usr/bin/env node

/**
 * Generates the bundled icon collection.
 *
 * Reads the curated list in icons.json, optimises each SVG, and writes
 * <out>/*.svg plus <out>/manifest.php into the calling plugin.
 *
 * The output directory and the text domain of the generated labels belong to the
 * caller, so both are arguments: --out and --domain.
 *
 * The manifest mirrors the shape core uses for its own icons
 * (wp-includes/assets/icon-library-manifest.php) so includes/Icons.php can loop
 * it straight into wp_register_icon().
 *
 * Icons must be filled and path-only: core's sanitize_icon_content() allows only
 * svg, path and polygon, and strips every stroke attribute. A stroke-based set
 * registers without error and renders broken.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const require = createRequire( import.meta.url );
const __dirname = path.dirname( fileURLToPath( import.meta.url ) );

const argument = ( name, fallback ) => {
	const index = process.argv.indexOf( `--${ name }` );

	return index === -1 ? fallback : process.argv[ index + 1 ];
};

const DOMAIN = argument( 'domain', 'default' );

// INIT_CWD is where the command was invoked, which is the consuming plugin even
// when a workspace filter runs this with the package as the working directory.
const OUT = path.resolve(
	process.env.INIT_CWD || process.cwd(),
	argument( 'out', 'assets/icons' )
);
const CONFIG = require( path.join( __dirname, '..', 'icons.json' ) );
const SOURCE = path.join(
	path.dirname(
		require.resolve( `${ CONFIG.source.package }/package.json` )
	),
	CONFIG.source.path
);

const svgo = {
	multipass: true,
	plugins: [
		{
			name: 'preset-default',
			params: { overrides: { removeViewBox: false } },
		},
		{
			name: 'removeAttrs',
			// wp_get_icon() sets width, height and the accessibility attributes when
			// it renders, so baking them in here would conflict with its choice.
			params: {
				attrs: '(class|id|style|width|height|aria-hidden|focusable|data-.*)',
			},
		},
		{ name: 'sortAttrs', params: { order: 'alphabetical' } },
	],
};

const title = ( slug ) =>
	slug
		.split( '-' )
		.map( ( word ) => word.charAt( 0 ).toUpperCase() + word.slice( 1 ) )
		.join( ' ' );

const php = ( value ) =>
	String( value ).replace( /\\/g, '\\\\' ).replace( /'/g, "\\'" );

function build() {
	fs.rmSync( OUT, { recursive: true, force: true } );
	fs.mkdirSync( OUT, { recursive: true } );

	const entries = [];
	const seen = new Set();

	for ( const [ category, config ] of Object.entries( CONFIG.categories ) ) {
		for ( const slug of config.icons ) {
			if ( seen.has( slug ) ) {
				process.stdout.write( `  duplicate, skipped: ${ slug }\n` );
				continue;
			}

			const source = path.join( SOURCE, `${ slug }.svg` );

			if ( ! fs.existsSync( source ) ) {
				process.stdout.write( `  missing, skipped:   ${ slug }\n` );
				continue;
			}

			const raw = fs.readFileSync( source, 'utf8' );
			const svg = optimize( raw, svgo ).data.trim();

			if (
				/<(?!svg|path|polygon|\/)/.test( svg ) ||
				/stroke/.test( svg )
			) {
				process.stdout.write( `  not path-only:      ${ slug }\n` );
				continue;
			}

			fs.writeFileSync( path.join( OUT, `${ slug }.svg` ), `${ svg }\n` );
			seen.add( slug );
			entries.push( { slug, label: title( slug ), category } );
		}
	}

	const rows = entries
		.map(
			( entry ) =>
				`\t'${ php( entry.slug ) }' => array(\n` +
				`\t\t'label'    => _x( '${ php(
					entry.label
				) }', 'icon label', '${ php( DOMAIN ) }' ),\n` +
				`\t\t'filePath' => '${ php( entry.slug ) }.svg',\n` +
				`\t\t'category' => '${ php( entry.category ) }',\n` +
				`\t),`
		)
		.join( '\n' );

	fs.writeFileSync(
		path.join( OUT, 'manifest.php' ),
		`<?php\n// This file is generated by bin/build-icons.js. Do not edit directly.\ndefined( 'ABSPATH' ) || exit;\n\nreturn array(\n${ rows }\n);\n`
	);

	// MIT requires the notice to travel with the copies.
	fs.copyFileSync(
		path.join(
			path.dirname(
				require.resolve( `${ CONFIG.source.package }/package.json` )
			),
			'LICENSE'
		),
		path.join( OUT, 'LICENSE' )
	);

	process.stdout.write( `\nWrote ${ entries.length } icons to ${ OUT }\n` );
}

build();
