<?php
// This file is generated by bin/build-icons.js. Do not edit directly.
defined( 'ABSPATH' ) || exit;

return array(
	'arrow-down' => array(
		'label'    => _x( 'Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down.svg',
		'category' => 'arrows',
	),
	'arrow-down-circle' => array(
		'label'    => _x( 'Arrow Down Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-circle.svg',
		'category' => 'arrows',
	),
	'arrow-down-left' => array(
		'label'    => _x( 'Arrow Down Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-left.svg',
		'category' => 'arrows',
	),
	'arrow-down-on-square' => array(
		'label'    => _x( 'Arrow Down On Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-on-square.svg',
		'category' => 'arrows',
	),
	'arrow-down-on-square-stack' => array(
		'label'    => _x( 'Arrow Down On Square Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-on-square-stack.svg',
		'category' => 'arrows',
	),
	'arrow-down-right' => array(
		'label'    => _x( 'Arrow Down Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-right.svg',
		'category' => 'arrows',
	),
	'arrow-down-tray' => array(
		'label'    => _x( 'Arrow Down Tray', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-down-tray.svg',
		'category' => 'arrows',
	),
	'arrow-left' => array(
		'label'    => _x( 'Arrow Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-left.svg',
		'category' => 'arrows',
	),
	'arrow-left-circle' => array(
		'label'    => _x( 'Arrow Left Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-left-circle.svg',
		'category' => 'arrows',
	),
	'arrow-left-end-on-rectangle' => array(
		'label'    => _x( 'Arrow Left End On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-left-end-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-left-on-rectangle' => array(
		'label'    => _x( 'Arrow Left On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-left-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-left-start-on-rectangle' => array(
		'label'    => _x( 'Arrow Left Start On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-left-start-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-long-down' => array(
		'label'    => _x( 'Arrow Long Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-long-down.svg',
		'category' => 'arrows',
	),
	'arrow-long-left' => array(
		'label'    => _x( 'Arrow Long Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-long-left.svg',
		'category' => 'arrows',
	),
	'arrow-long-right' => array(
		'label'    => _x( 'Arrow Long Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-long-right.svg',
		'category' => 'arrows',
	),
	'arrow-long-up' => array(
		'label'    => _x( 'Arrow Long Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-long-up.svg',
		'category' => 'arrows',
	),
	'arrow-path' => array(
		'label'    => _x( 'Arrow Path', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-path.svg',
		'category' => 'arrows',
	),
	'arrow-path-rounded-square' => array(
		'label'    => _x( 'Arrow Path Rounded Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-path-rounded-square.svg',
		'category' => 'arrows',
	),
	'arrow-right' => array(
		'label'    => _x( 'Arrow Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-right.svg',
		'category' => 'arrows',
	),
	'arrow-right-circle' => array(
		'label'    => _x( 'Arrow Right Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-right-circle.svg',
		'category' => 'arrows',
	),
	'arrow-right-end-on-rectangle' => array(
		'label'    => _x( 'Arrow Right End On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-right-end-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-right-on-rectangle' => array(
		'label'    => _x( 'Arrow Right On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-right-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-right-start-on-rectangle' => array(
		'label'    => _x( 'Arrow Right Start On Rectangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-right-start-on-rectangle.svg',
		'category' => 'arrows',
	),
	'arrow-small-down' => array(
		'label'    => _x( 'Arrow Small Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-small-down.svg',
		'category' => 'arrows',
	),
	'arrow-small-left' => array(
		'label'    => _x( 'Arrow Small Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-small-left.svg',
		'category' => 'arrows',
	),
	'arrow-small-right' => array(
		'label'    => _x( 'Arrow Small Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-small-right.svg',
		'category' => 'arrows',
	),
	'arrow-small-up' => array(
		'label'    => _x( 'Arrow Small Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-small-up.svg',
		'category' => 'arrows',
	),
	'arrow-top-right-on-square' => array(
		'label'    => _x( 'Arrow Top Right On Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-top-right-on-square.svg',
		'category' => 'arrows',
	),
	'arrow-trending-down' => array(
		'label'    => _x( 'Arrow Trending Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-trending-down.svg',
		'category' => 'arrows',
	),
	'arrow-trending-up' => array(
		'label'    => _x( 'Arrow Trending Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-trending-up.svg',
		'category' => 'arrows',
	),
	'arrow-turn-down-left' => array(
		'label'    => _x( 'Arrow Turn Down Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-down-left.svg',
		'category' => 'arrows',
	),
	'arrow-turn-down-right' => array(
		'label'    => _x( 'Arrow Turn Down Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-down-right.svg',
		'category' => 'arrows',
	),
	'arrow-turn-left-down' => array(
		'label'    => _x( 'Arrow Turn Left Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-left-down.svg',
		'category' => 'arrows',
	),
	'arrow-turn-left-up' => array(
		'label'    => _x( 'Arrow Turn Left Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-left-up.svg',
		'category' => 'arrows',
	),
	'arrow-turn-right-down' => array(
		'label'    => _x( 'Arrow Turn Right Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-right-down.svg',
		'category' => 'arrows',
	),
	'arrow-turn-right-up' => array(
		'label'    => _x( 'Arrow Turn Right Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-right-up.svg',
		'category' => 'arrows',
	),
	'arrow-turn-up-left' => array(
		'label'    => _x( 'Arrow Turn Up Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-up-left.svg',
		'category' => 'arrows',
	),
	'arrow-turn-up-right' => array(
		'label'    => _x( 'Arrow Turn Up Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-turn-up-right.svg',
		'category' => 'arrows',
	),
	'arrow-up' => array(
		'label'    => _x( 'Arrow Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up.svg',
		'category' => 'arrows',
	),
	'arrow-up-circle' => array(
		'label'    => _x( 'Arrow Up Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-circle.svg',
		'category' => 'arrows',
	),
	'arrow-up-left' => array(
		'label'    => _x( 'Arrow Up Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-left.svg',
		'category' => 'arrows',
	),
	'arrow-up-on-square' => array(
		'label'    => _x( 'Arrow Up On Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-on-square.svg',
		'category' => 'arrows',
	),
	'arrow-up-on-square-stack' => array(
		'label'    => _x( 'Arrow Up On Square Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-on-square-stack.svg',
		'category' => 'arrows',
	),
	'arrow-up-right' => array(
		'label'    => _x( 'Arrow Up Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-right.svg',
		'category' => 'arrows',
	),
	'arrow-up-tray' => array(
		'label'    => _x( 'Arrow Up Tray', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-up-tray.svg',
		'category' => 'arrows',
	),
	'arrow-uturn-down' => array(
		'label'    => _x( 'Arrow Uturn Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-uturn-down.svg',
		'category' => 'arrows',
	),
	'arrow-uturn-left' => array(
		'label'    => _x( 'Arrow Uturn Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-uturn-left.svg',
		'category' => 'arrows',
	),
	'arrow-uturn-right' => array(
		'label'    => _x( 'Arrow Uturn Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-uturn-right.svg',
		'category' => 'arrows',
	),
	'arrow-uturn-up' => array(
		'label'    => _x( 'Arrow Uturn Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrow-uturn-up.svg',
		'category' => 'arrows',
	),
	'arrows-pointing-in' => array(
		'label'    => _x( 'Arrows Pointing In', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrows-pointing-in.svg',
		'category' => 'arrows',
	),
	'arrows-pointing-out' => array(
		'label'    => _x( 'Arrows Pointing Out', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrows-pointing-out.svg',
		'category' => 'arrows',
	),
	'arrows-right-left' => array(
		'label'    => _x( 'Arrows Right Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrows-right-left.svg',
		'category' => 'arrows',
	),
	'arrows-up-down' => array(
		'label'    => _x( 'Arrows Up Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'arrows-up-down.svg',
		'category' => 'arrows',
	),
	'chevron-double-down' => array(
		'label'    => _x( 'Chevron Double Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-double-down.svg',
		'category' => 'arrows',
	),
	'chevron-double-left' => array(
		'label'    => _x( 'Chevron Double Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-double-left.svg',
		'category' => 'arrows',
	),
	'chevron-double-right' => array(
		'label'    => _x( 'Chevron Double Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-double-right.svg',
		'category' => 'arrows',
	),
	'chevron-double-up' => array(
		'label'    => _x( 'Chevron Double Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-double-up.svg',
		'category' => 'arrows',
	),
	'chevron-down' => array(
		'label'    => _x( 'Chevron Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-down.svg',
		'category' => 'arrows',
	),
	'chevron-left' => array(
		'label'    => _x( 'Chevron Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-left.svg',
		'category' => 'arrows',
	),
	'chevron-right' => array(
		'label'    => _x( 'Chevron Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-right.svg',
		'category' => 'arrows',
	),
	'chevron-up' => array(
		'label'    => _x( 'Chevron Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-up.svg',
		'category' => 'arrows',
	),
	'chevron-up-down' => array(
		'label'    => _x( 'Chevron Up Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'chevron-up-down.svg',
		'category' => 'arrows',
	),
	'backward' => array(
		'label'    => _x( 'Backward', 'icon label', 'ever-blocks' ),
		'filePath' => 'backward.svg',
		'category' => 'media',
	),
	'camera' => array(
		'label'    => _x( 'Camera', 'icon label', 'ever-blocks' ),
		'filePath' => 'camera.svg',
		'category' => 'media',
	),
	'film' => array(
		'label'    => _x( 'Film', 'icon label', 'ever-blocks' ),
		'filePath' => 'film.svg',
		'category' => 'media',
	),
	'forward' => array(
		'label'    => _x( 'Forward', 'icon label', 'ever-blocks' ),
		'filePath' => 'forward.svg',
		'category' => 'media',
	),
	'gif' => array(
		'label'    => _x( 'Gif', 'icon label', 'ever-blocks' ),
		'filePath' => 'gif.svg',
		'category' => 'media',
	),
	'gift' => array(
		'label'    => _x( 'Gift', 'icon label', 'ever-blocks' ),
		'filePath' => 'gift.svg',
		'category' => 'media',
	),
	'gift-top' => array(
		'label'    => _x( 'Gift Top', 'icon label', 'ever-blocks' ),
		'filePath' => 'gift-top.svg',
		'category' => 'media',
	),
	'microphone' => array(
		'label'    => _x( 'Microphone', 'icon label', 'ever-blocks' ),
		'filePath' => 'microphone.svg',
		'category' => 'media',
	),
	'musical-note' => array(
		'label'    => _x( 'Musical Note', 'icon label', 'ever-blocks' ),
		'filePath' => 'musical-note.svg',
		'category' => 'media',
	),
	'pause' => array(
		'label'    => _x( 'Pause', 'icon label', 'ever-blocks' ),
		'filePath' => 'pause.svg',
		'category' => 'media',
	),
	'pause-circle' => array(
		'label'    => _x( 'Pause Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'pause-circle.svg',
		'category' => 'media',
	),
	'photo' => array(
		'label'    => _x( 'Photo', 'icon label', 'ever-blocks' ),
		'filePath' => 'photo.svg',
		'category' => 'media',
	),
	'play' => array(
		'label'    => _x( 'Play', 'icon label', 'ever-blocks' ),
		'filePath' => 'play.svg',
		'category' => 'media',
	),
	'play-circle' => array(
		'label'    => _x( 'Play Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'play-circle.svg',
		'category' => 'media',
	),
	'play-pause' => array(
		'label'    => _x( 'Play Pause', 'icon label', 'ever-blocks' ),
		'filePath' => 'play-pause.svg',
		'category' => 'media',
	),
	'speaker-wave' => array(
		'label'    => _x( 'Speaker Wave', 'icon label', 'ever-blocks' ),
		'filePath' => 'speaker-wave.svg',
		'category' => 'media',
	),
	'speaker-x-mark' => array(
		'label'    => _x( 'Speaker X Mark', 'icon label', 'ever-blocks' ),
		'filePath' => 'speaker-x-mark.svg',
		'category' => 'media',
	),
	'stop' => array(
		'label'    => _x( 'Stop', 'icon label', 'ever-blocks' ),
		'filePath' => 'stop.svg',
		'category' => 'media',
	),
	'stop-circle' => array(
		'label'    => _x( 'Stop Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'stop-circle.svg',
		'category' => 'media',
	),
	'tv' => array(
		'label'    => _x( 'Tv', 'icon label', 'ever-blocks' ),
		'filePath' => 'tv.svg',
		'category' => 'media',
	),
	'video-camera' => array(
		'label'    => _x( 'Video Camera', 'icon label', 'ever-blocks' ),
		'filePath' => 'video-camera.svg',
		'category' => 'media',
	),
	'video-camera-slash' => array(
		'label'    => _x( 'Video Camera Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'video-camera-slash.svg',
		'category' => 'media',
	),
	'banknotes' => array(
		'label'    => _x( 'Banknotes', 'icon label', 'ever-blocks' ),
		'filePath' => 'banknotes.svg',
		'category' => 'commerce',
	),
	'building-storefront' => array(
		'label'    => _x( 'Building Storefront', 'icon label', 'ever-blocks' ),
		'filePath' => 'building-storefront.svg',
		'category' => 'commerce',
	),
	'credit-card' => array(
		'label'    => _x( 'Credit Card', 'icon label', 'ever-blocks' ),
		'filePath' => 'credit-card.svg',
		'category' => 'commerce',
	),
	'currency-bangladeshi' => array(
		'label'    => _x( 'Currency Bangladeshi', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-bangladeshi.svg',
		'category' => 'commerce',
	),
	'currency-dollar' => array(
		'label'    => _x( 'Currency Dollar', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-dollar.svg',
		'category' => 'commerce',
	),
	'currency-euro' => array(
		'label'    => _x( 'Currency Euro', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-euro.svg',
		'category' => 'commerce',
	),
	'currency-pound' => array(
		'label'    => _x( 'Currency Pound', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-pound.svg',
		'category' => 'commerce',
	),
	'currency-rupee' => array(
		'label'    => _x( 'Currency Rupee', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-rupee.svg',
		'category' => 'commerce',
	),
	'currency-yen' => array(
		'label'    => _x( 'Currency Yen', 'icon label', 'ever-blocks' ),
		'filePath' => 'currency-yen.svg',
		'category' => 'commerce',
	),
	'percent-badge' => array(
		'label'    => _x( 'Percent Badge', 'icon label', 'ever-blocks' ),
		'filePath' => 'percent-badge.svg',
		'category' => 'commerce',
	),
	'receipt-percent' => array(
		'label'    => _x( 'Receipt Percent', 'icon label', 'ever-blocks' ),
		'filePath' => 'receipt-percent.svg',
		'category' => 'commerce',
	),
	'receipt-refund' => array(
		'label'    => _x( 'Receipt Refund', 'icon label', 'ever-blocks' ),
		'filePath' => 'receipt-refund.svg',
		'category' => 'commerce',
	),
	'scale' => array(
		'label'    => _x( 'Scale', 'icon label', 'ever-blocks' ),
		'filePath' => 'scale.svg',
		'category' => 'commerce',
	),
	'shopping-bag' => array(
		'label'    => _x( 'Shopping Bag', 'icon label', 'ever-blocks' ),
		'filePath' => 'shopping-bag.svg',
		'category' => 'commerce',
	),
	'shopping-cart' => array(
		'label'    => _x( 'Shopping Cart', 'icon label', 'ever-blocks' ),
		'filePath' => 'shopping-cart.svg',
		'category' => 'commerce',
	),
	'tag' => array(
		'label'    => _x( 'Tag', 'icon label', 'ever-blocks' ),
		'filePath' => 'tag.svg',
		'category' => 'commerce',
	),
	'ticket' => array(
		'label'    => _x( 'Ticket', 'icon label', 'ever-blocks' ),
		'filePath' => 'ticket.svg',
		'category' => 'commerce',
	),
	'truck' => array(
		'label'    => _x( 'Truck', 'icon label', 'ever-blocks' ),
		'filePath' => 'truck.svg',
		'category' => 'commerce',
	),
	'wallet' => array(
		'label'    => _x( 'Wallet', 'icon label', 'ever-blocks' ),
		'filePath' => 'wallet.svg',
		'category' => 'commerce',
	),
	'at-symbol' => array(
		'label'    => _x( 'At Symbol', 'icon label', 'ever-blocks' ),
		'filePath' => 'at-symbol.svg',
		'category' => 'communication',
	),
	'bell' => array(
		'label'    => _x( 'Bell', 'icon label', 'ever-blocks' ),
		'filePath' => 'bell.svg',
		'category' => 'communication',
	),
	'bell-alert' => array(
		'label'    => _x( 'Bell Alert', 'icon label', 'ever-blocks' ),
		'filePath' => 'bell-alert.svg',
		'category' => 'communication',
	),
	'bell-slash' => array(
		'label'    => _x( 'Bell Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'bell-slash.svg',
		'category' => 'communication',
	),
	'bell-snooze' => array(
		'label'    => _x( 'Bell Snooze', 'icon label', 'ever-blocks' ),
		'filePath' => 'bell-snooze.svg',
		'category' => 'communication',
	),
	'chat-bubble-bottom-center' => array(
		'label'    => _x( 'Chat Bubble Bottom Center', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-bottom-center.svg',
		'category' => 'communication',
	),
	'chat-bubble-bottom-center-text' => array(
		'label'    => _x( 'Chat Bubble Bottom Center Text', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-bottom-center-text.svg',
		'category' => 'communication',
	),
	'chat-bubble-left' => array(
		'label'    => _x( 'Chat Bubble Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-left.svg',
		'category' => 'communication',
	),
	'chat-bubble-left-ellipsis' => array(
		'label'    => _x( 'Chat Bubble Left Ellipsis', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-left-ellipsis.svg',
		'category' => 'communication',
	),
	'chat-bubble-left-right' => array(
		'label'    => _x( 'Chat Bubble Left Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-left-right.svg',
		'category' => 'communication',
	),
	'chat-bubble-oval-left' => array(
		'label'    => _x( 'Chat Bubble Oval Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-oval-left.svg',
		'category' => 'communication',
	),
	'chat-bubble-oval-left-ellipsis' => array(
		'label'    => _x( 'Chat Bubble Oval Left Ellipsis', 'icon label', 'ever-blocks' ),
		'filePath' => 'chat-bubble-oval-left-ellipsis.svg',
		'category' => 'communication',
	),
	'envelope' => array(
		'label'    => _x( 'Envelope', 'icon label', 'ever-blocks' ),
		'filePath' => 'envelope.svg',
		'category' => 'communication',
	),
	'envelope-open' => array(
		'label'    => _x( 'Envelope Open', 'icon label', 'ever-blocks' ),
		'filePath' => 'envelope-open.svg',
		'category' => 'communication',
	),
	'inbox' => array(
		'label'    => _x( 'Inbox', 'icon label', 'ever-blocks' ),
		'filePath' => 'inbox.svg',
		'category' => 'communication',
	),
	'inbox-arrow-down' => array(
		'label'    => _x( 'Inbox Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'inbox-arrow-down.svg',
		'category' => 'communication',
	),
	'inbox-stack' => array(
		'label'    => _x( 'Inbox Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'inbox-stack.svg',
		'category' => 'communication',
	),
	'language' => array(
		'label'    => _x( 'Language', 'icon label', 'ever-blocks' ),
		'filePath' => 'language.svg',
		'category' => 'communication',
	),
	'megaphone' => array(
		'label'    => _x( 'Megaphone', 'icon label', 'ever-blocks' ),
		'filePath' => 'megaphone.svg',
		'category' => 'communication',
	),
	'paper-airplane' => array(
		'label'    => _x( 'Paper Airplane', 'icon label', 'ever-blocks' ),
		'filePath' => 'paper-airplane.svg',
		'category' => 'communication',
	),
	'phone' => array(
		'label'    => _x( 'Phone', 'icon label', 'ever-blocks' ),
		'filePath' => 'phone.svg',
		'category' => 'communication',
	),
	'phone-arrow-down-left' => array(
		'label'    => _x( 'Phone Arrow Down Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'phone-arrow-down-left.svg',
		'category' => 'communication',
	),
	'phone-arrow-up-right' => array(
		'label'    => _x( 'Phone Arrow Up Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'phone-arrow-up-right.svg',
		'category' => 'communication',
	),
	'phone-x-mark' => array(
		'label'    => _x( 'Phone X Mark', 'icon label', 'ever-blocks' ),
		'filePath' => 'phone-x-mark.svg',
		'category' => 'communication',
	),
	'rss' => array(
		'label'    => _x( 'Rss', 'icon label', 'ever-blocks' ),
		'filePath' => 'rss.svg',
		'category' => 'communication',
	),
	'share' => array(
		'label'    => _x( 'Share', 'icon label', 'ever-blocks' ),
		'filePath' => 'share.svg',
		'category' => 'communication',
	),
	'signal' => array(
		'label'    => _x( 'Signal', 'icon label', 'ever-blocks' ),
		'filePath' => 'signal.svg',
		'category' => 'communication',
	),
	'signal-slash' => array(
		'label'    => _x( 'Signal Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'signal-slash.svg',
		'category' => 'communication',
	),
	'wifi' => array(
		'label'    => _x( 'Wifi', 'icon label', 'ever-blocks' ),
		'filePath' => 'wifi.svg',
		'category' => 'communication',
	),
	'archive-box' => array(
		'label'    => _x( 'Archive Box', 'icon label', 'ever-blocks' ),
		'filePath' => 'archive-box.svg',
		'category' => 'files',
	),
	'archive-box-arrow-down' => array(
		'label'    => _x( 'Archive Box Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'archive-box-arrow-down.svg',
		'category' => 'files',
	),
	'archive-box-x-mark' => array(
		'label'    => _x( 'Archive Box X Mark', 'icon label', 'ever-blocks' ),
		'filePath' => 'archive-box-x-mark.svg',
		'category' => 'files',
	),
	'book-open' => array(
		'label'    => _x( 'Book Open', 'icon label', 'ever-blocks' ),
		'filePath' => 'book-open.svg',
		'category' => 'files',
	),
	'bookmark' => array(
		'label'    => _x( 'Bookmark', 'icon label', 'ever-blocks' ),
		'filePath' => 'bookmark.svg',
		'category' => 'files',
	),
	'bookmark-slash' => array(
		'label'    => _x( 'Bookmark Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'bookmark-slash.svg',
		'category' => 'files',
	),
	'bookmark-square' => array(
		'label'    => _x( 'Bookmark Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'bookmark-square.svg',
		'category' => 'files',
	),
	'clipboard' => array(
		'label'    => _x( 'Clipboard', 'icon label', 'ever-blocks' ),
		'filePath' => 'clipboard.svg',
		'category' => 'files',
	),
	'clipboard-document' => array(
		'label'    => _x( 'Clipboard Document', 'icon label', 'ever-blocks' ),
		'filePath' => 'clipboard-document.svg',
		'category' => 'files',
	),
	'clipboard-document-check' => array(
		'label'    => _x( 'Clipboard Document Check', 'icon label', 'ever-blocks' ),
		'filePath' => 'clipboard-document-check.svg',
		'category' => 'files',
	),
	'clipboard-document-list' => array(
		'label'    => _x( 'Clipboard Document List', 'icon label', 'ever-blocks' ),
		'filePath' => 'clipboard-document-list.svg',
		'category' => 'files',
	),
	'document' => array(
		'label'    => _x( 'Document', 'icon label', 'ever-blocks' ),
		'filePath' => 'document.svg',
		'category' => 'files',
	),
	'document-arrow-down' => array(
		'label'    => _x( 'Document Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-arrow-down.svg',
		'category' => 'files',
	),
	'document-arrow-up' => array(
		'label'    => _x( 'Document Arrow Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-arrow-up.svg',
		'category' => 'files',
	),
	'document-chart-bar' => array(
		'label'    => _x( 'Document Chart Bar', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-chart-bar.svg',
		'category' => 'files',
	),
	'document-check' => array(
		'label'    => _x( 'Document Check', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-check.svg',
		'category' => 'files',
	),
	'document-currency-bangladeshi' => array(
		'label'    => _x( 'Document Currency Bangladeshi', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-bangladeshi.svg',
		'category' => 'files',
	),
	'document-currency-dollar' => array(
		'label'    => _x( 'Document Currency Dollar', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-dollar.svg',
		'category' => 'files',
	),
	'document-currency-euro' => array(
		'label'    => _x( 'Document Currency Euro', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-euro.svg',
		'category' => 'files',
	),
	'document-currency-pound' => array(
		'label'    => _x( 'Document Currency Pound', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-pound.svg',
		'category' => 'files',
	),
	'document-currency-rupee' => array(
		'label'    => _x( 'Document Currency Rupee', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-rupee.svg',
		'category' => 'files',
	),
	'document-currency-yen' => array(
		'label'    => _x( 'Document Currency Yen', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-currency-yen.svg',
		'category' => 'files',
	),
	'document-duplicate' => array(
		'label'    => _x( 'Document Duplicate', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-duplicate.svg',
		'category' => 'files',
	),
	'document-magnifying-glass' => array(
		'label'    => _x( 'Document Magnifying Glass', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-magnifying-glass.svg',
		'category' => 'files',
	),
	'document-minus' => array(
		'label'    => _x( 'Document Minus', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-minus.svg',
		'category' => 'files',
	),
	'document-plus' => array(
		'label'    => _x( 'Document Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-plus.svg',
		'category' => 'files',
	),
	'document-text' => array(
		'label'    => _x( 'Document Text', 'icon label', 'ever-blocks' ),
		'filePath' => 'document-text.svg',
		'category' => 'files',
	),
	'folder' => array(
		'label'    => _x( 'Folder', 'icon label', 'ever-blocks' ),
		'filePath' => 'folder.svg',
		'category' => 'files',
	),
	'folder-arrow-down' => array(
		'label'    => _x( 'Folder Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'folder-arrow-down.svg',
		'category' => 'files',
	),
	'folder-minus' => array(
		'label'    => _x( 'Folder Minus', 'icon label', 'ever-blocks' ),
		'filePath' => 'folder-minus.svg',
		'category' => 'files',
	),
	'folder-open' => array(
		'label'    => _x( 'Folder Open', 'icon label', 'ever-blocks' ),
		'filePath' => 'folder-open.svg',
		'category' => 'files',
	),
	'folder-plus' => array(
		'label'    => _x( 'Folder Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'folder-plus.svg',
		'category' => 'files',
	),
	'newspaper' => array(
		'label'    => _x( 'Newspaper', 'icon label', 'ever-blocks' ),
		'filePath' => 'newspaper.svg',
		'category' => 'files',
	),
	'paper-clip' => array(
		'label'    => _x( 'Paper Clip', 'icon label', 'ever-blocks' ),
		'filePath' => 'paper-clip.svg',
		'category' => 'files',
	),
	'printer' => array(
		'label'    => _x( 'Printer', 'icon label', 'ever-blocks' ),
		'filePath' => 'printer.svg',
		'category' => 'files',
	),
	'scissors' => array(
		'label'    => _x( 'Scissors', 'icon label', 'ever-blocks' ),
		'filePath' => 'scissors.svg',
		'category' => 'files',
	),
	'academic-cap' => array(
		'label'    => _x( 'Academic Cap', 'icon label', 'ever-blocks' ),
		'filePath' => 'academic-cap.svg',
		'category' => 'users',
	),
	'briefcase' => array(
		'label'    => _x( 'Briefcase', 'icon label', 'ever-blocks' ),
		'filePath' => 'briefcase.svg',
		'category' => 'users',
	),
	'face-frown' => array(
		'label'    => _x( 'Face Frown', 'icon label', 'ever-blocks' ),
		'filePath' => 'face-frown.svg',
		'category' => 'users',
	),
	'face-smile' => array(
		'label'    => _x( 'Face Smile', 'icon label', 'ever-blocks' ),
		'filePath' => 'face-smile.svg',
		'category' => 'users',
	),
	'hand-raised' => array(
		'label'    => _x( 'Hand Raised', 'icon label', 'ever-blocks' ),
		'filePath' => 'hand-raised.svg',
		'category' => 'users',
	),
	'hand-thumb-down' => array(
		'label'    => _x( 'Hand Thumb Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'hand-thumb-down.svg',
		'category' => 'users',
	),
	'hand-thumb-up' => array(
		'label'    => _x( 'Hand Thumb Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'hand-thumb-up.svg',
		'category' => 'users',
	),
	'identification' => array(
		'label'    => _x( 'Identification', 'icon label', 'ever-blocks' ),
		'filePath' => 'identification.svg',
		'category' => 'users',
	),
	'user' => array(
		'label'    => _x( 'User', 'icon label', 'ever-blocks' ),
		'filePath' => 'user.svg',
		'category' => 'users',
	),
	'user-circle' => array(
		'label'    => _x( 'User Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'user-circle.svg',
		'category' => 'users',
	),
	'user-group' => array(
		'label'    => _x( 'User Group', 'icon label', 'ever-blocks' ),
		'filePath' => 'user-group.svg',
		'category' => 'users',
	),
	'user-minus' => array(
		'label'    => _x( 'User Minus', 'icon label', 'ever-blocks' ),
		'filePath' => 'user-minus.svg',
		'category' => 'users',
	),
	'user-plus' => array(
		'label'    => _x( 'User Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'user-plus.svg',
		'category' => 'users',
	),
	'users' => array(
		'label'    => _x( 'Users', 'icon label', 'ever-blocks' ),
		'filePath' => 'users.svg',
		'category' => 'users',
	),
	'bars-2' => array(
		'label'    => _x( 'Bars 2', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-2.svg',
		'category' => 'editor',
	),
	'bars-3' => array(
		'label'    => _x( 'Bars 3', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-3.svg',
		'category' => 'editor',
	),
	'bars-3-bottom-left' => array(
		'label'    => _x( 'Bars 3 Bottom Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-3-bottom-left.svg',
		'category' => 'editor',
	),
	'bars-3-bottom-right' => array(
		'label'    => _x( 'Bars 3 Bottom Right', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-3-bottom-right.svg',
		'category' => 'editor',
	),
	'bars-3-center-left' => array(
		'label'    => _x( 'Bars 3 Center Left', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-3-center-left.svg',
		'category' => 'editor',
	),
	'bars-4' => array(
		'label'    => _x( 'Bars 4', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-4.svg',
		'category' => 'editor',
	),
	'bars-arrow-down' => array(
		'label'    => _x( 'Bars Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-arrow-down.svg',
		'category' => 'editor',
	),
	'bars-arrow-up' => array(
		'label'    => _x( 'Bars Arrow Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'bars-arrow-up.svg',
		'category' => 'editor',
	),
	'bold' => array(
		'label'    => _x( 'Bold', 'icon label', 'ever-blocks' ),
		'filePath' => 'bold.svg',
		'category' => 'editor',
	),
	'eye-dropper' => array(
		'label'    => _x( 'Eye Dropper', 'icon label', 'ever-blocks' ),
		'filePath' => 'eye-dropper.svg',
		'category' => 'editor',
	),
	'h1' => array(
		'label'    => _x( 'H1', 'icon label', 'ever-blocks' ),
		'filePath' => 'h1.svg',
		'category' => 'editor',
	),
	'h2' => array(
		'label'    => _x( 'H2', 'icon label', 'ever-blocks' ),
		'filePath' => 'h2.svg',
		'category' => 'editor',
	),
	'h3' => array(
		'label'    => _x( 'H3', 'icon label', 'ever-blocks' ),
		'filePath' => 'h3.svg',
		'category' => 'editor',
	),
	'hashtag' => array(
		'label'    => _x( 'Hashtag', 'icon label', 'ever-blocks' ),
		'filePath' => 'hashtag.svg',
		'category' => 'editor',
	),
	'italic' => array(
		'label'    => _x( 'Italic', 'icon label', 'ever-blocks' ),
		'filePath' => 'italic.svg',
		'category' => 'editor',
	),
	'link' => array(
		'label'    => _x( 'Link', 'icon label', 'ever-blocks' ),
		'filePath' => 'link.svg',
		'category' => 'editor',
	),
	'link-slash' => array(
		'label'    => _x( 'Link Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'link-slash.svg',
		'category' => 'editor',
	),
	'list-bullet' => array(
		'label'    => _x( 'List Bullet', 'icon label', 'ever-blocks' ),
		'filePath' => 'list-bullet.svg',
		'category' => 'editor',
	),
	'numbered-list' => array(
		'label'    => _x( 'Numbered List', 'icon label', 'ever-blocks' ),
		'filePath' => 'numbered-list.svg',
		'category' => 'editor',
	),
	'paint-brush' => array(
		'label'    => _x( 'Paint Brush', 'icon label', 'ever-blocks' ),
		'filePath' => 'paint-brush.svg',
		'category' => 'editor',
	),
	'pencil' => array(
		'label'    => _x( 'Pencil', 'icon label', 'ever-blocks' ),
		'filePath' => 'pencil.svg',
		'category' => 'editor',
	),
	'pencil-square' => array(
		'label'    => _x( 'Pencil Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'pencil-square.svg',
		'category' => 'editor',
	),
	'strikethrough' => array(
		'label'    => _x( 'Strikethrough', 'icon label', 'ever-blocks' ),
		'filePath' => 'strikethrough.svg',
		'category' => 'editor',
	),
	'swatch' => array(
		'label'    => _x( 'Swatch', 'icon label', 'ever-blocks' ),
		'filePath' => 'swatch.svg',
		'category' => 'editor',
	),
	'underline' => array(
		'label'    => _x( 'Underline', 'icon label', 'ever-blocks' ),
		'filePath' => 'underline.svg',
		'category' => 'editor',
	),
	'variable' => array(
		'label'    => _x( 'Variable', 'icon label', 'ever-blocks' ),
		'filePath' => 'variable.svg',
		'category' => 'editor',
	),
	'circle-stack' => array(
		'label'    => _x( 'Circle Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'circle-stack.svg',
		'category' => 'layout',
	),
	'cube' => array(
		'label'    => _x( 'Cube', 'icon label', 'ever-blocks' ),
		'filePath' => 'cube.svg',
		'category' => 'layout',
	),
	'cube-transparent' => array(
		'label'    => _x( 'Cube Transparent', 'icon label', 'ever-blocks' ),
		'filePath' => 'cube-transparent.svg',
		'category' => 'layout',
	),
	'divide' => array(
		'label'    => _x( 'Divide', 'icon label', 'ever-blocks' ),
		'filePath' => 'divide.svg',
		'category' => 'layout',
	),
	'equals' => array(
		'label'    => _x( 'Equals', 'icon label', 'ever-blocks' ),
		'filePath' => 'equals.svg',
		'category' => 'layout',
	),
	'queue-list' => array(
		'label'    => _x( 'Queue List', 'icon label', 'ever-blocks' ),
		'filePath' => 'queue-list.svg',
		'category' => 'layout',
	),
	'rectangle-group' => array(
		'label'    => _x( 'Rectangle Group', 'icon label', 'ever-blocks' ),
		'filePath' => 'rectangle-group.svg',
		'category' => 'layout',
	),
	'rectangle-stack' => array(
		'label'    => _x( 'Rectangle Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'rectangle-stack.svg',
		'category' => 'layout',
	),
	'square-2-stack' => array(
		'label'    => _x( 'Square 2 Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'square-2-stack.svg',
		'category' => 'layout',
	),
	'square-3-stack-3d' => array(
		'label'    => _x( 'Square 3 Stack 3d', 'icon label', 'ever-blocks' ),
		'filePath' => 'square-3-stack-3d.svg',
		'category' => 'layout',
	),
	'squares-2x2' => array(
		'label'    => _x( 'Squares 2x2', 'icon label', 'ever-blocks' ),
		'filePath' => 'squares-2x2.svg',
		'category' => 'layout',
	),
	'squares-plus' => array(
		'label'    => _x( 'Squares Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'squares-plus.svg',
		'category' => 'layout',
	),
	'table-cells' => array(
		'label'    => _x( 'Table Cells', 'icon label', 'ever-blocks' ),
		'filePath' => 'table-cells.svg',
		'category' => 'layout',
	),
	'view-columns' => array(
		'label'    => _x( 'View Columns', 'icon label', 'ever-blocks' ),
		'filePath' => 'view-columns.svg',
		'category' => 'layout',
	),
	'window' => array(
		'label'    => _x( 'Window', 'icon label', 'ever-blocks' ),
		'filePath' => 'window.svg',
		'category' => 'layout',
	),
	'calculator' => array(
		'label'    => _x( 'Calculator', 'icon label', 'ever-blocks' ),
		'filePath' => 'calculator.svg',
		'category' => 'charts',
	),
	'chart-bar' => array(
		'label'    => _x( 'Chart Bar', 'icon label', 'ever-blocks' ),
		'filePath' => 'chart-bar.svg',
		'category' => 'charts',
	),
	'chart-bar-square' => array(
		'label'    => _x( 'Chart Bar Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'chart-bar-square.svg',
		'category' => 'charts',
	),
	'chart-pie' => array(
		'label'    => _x( 'Chart Pie', 'icon label', 'ever-blocks' ),
		'filePath' => 'chart-pie.svg',
		'category' => 'charts',
	),
	'presentation-chart-bar' => array(
		'label'    => _x( 'Presentation Chart Bar', 'icon label', 'ever-blocks' ),
		'filePath' => 'presentation-chart-bar.svg',
		'category' => 'charts',
	),
	'presentation-chart-line' => array(
		'label'    => _x( 'Presentation Chart Line', 'icon label', 'ever-blocks' ),
		'filePath' => 'presentation-chart-line.svg',
		'category' => 'charts',
	),
	'calendar' => array(
		'label'    => _x( 'Calendar', 'icon label', 'ever-blocks' ),
		'filePath' => 'calendar.svg',
		'category' => 'time',
	),
	'calendar-date-range' => array(
		'label'    => _x( 'Calendar Date Range', 'icon label', 'ever-blocks' ),
		'filePath' => 'calendar-date-range.svg',
		'category' => 'time',
	),
	'calendar-days' => array(
		'label'    => _x( 'Calendar Days', 'icon label', 'ever-blocks' ),
		'filePath' => 'calendar-days.svg',
		'category' => 'time',
	),
	'clock' => array(
		'label'    => _x( 'Clock', 'icon label', 'ever-blocks' ),
		'filePath' => 'clock.svg',
		'category' => 'time',
	),
	'building-library' => array(
		'label'    => _x( 'Building Library', 'icon label', 'ever-blocks' ),
		'filePath' => 'building-library.svg',
		'category' => 'places',
	),
	'building-office' => array(
		'label'    => _x( 'Building Office', 'icon label', 'ever-blocks' ),
		'filePath' => 'building-office.svg',
		'category' => 'places',
	),
	'building-office-2' => array(
		'label'    => _x( 'Building Office 2', 'icon label', 'ever-blocks' ),
		'filePath' => 'building-office-2.svg',
		'category' => 'places',
	),
	'globe-alt' => array(
		'label'    => _x( 'Globe Alt', 'icon label', 'ever-blocks' ),
		'filePath' => 'globe-alt.svg',
		'category' => 'places',
	),
	'globe-americas' => array(
		'label'    => _x( 'Globe Americas', 'icon label', 'ever-blocks' ),
		'filePath' => 'globe-americas.svg',
		'category' => 'places',
	),
	'globe-asia-australia' => array(
		'label'    => _x( 'Globe Asia Australia', 'icon label', 'ever-blocks' ),
		'filePath' => 'globe-asia-australia.svg',
		'category' => 'places',
	),
	'globe-europe-africa' => array(
		'label'    => _x( 'Globe Europe Africa', 'icon label', 'ever-blocks' ),
		'filePath' => 'globe-europe-africa.svg',
		'category' => 'places',
	),
	'home' => array(
		'label'    => _x( 'Home', 'icon label', 'ever-blocks' ),
		'filePath' => 'home.svg',
		'category' => 'places',
	),
	'home-modern' => array(
		'label'    => _x( 'Home Modern', 'icon label', 'ever-blocks' ),
		'filePath' => 'home-modern.svg',
		'category' => 'places',
	),
	'map' => array(
		'label'    => _x( 'Map', 'icon label', 'ever-blocks' ),
		'filePath' => 'map.svg',
		'category' => 'places',
	),
	'map-pin' => array(
		'label'    => _x( 'Map Pin', 'icon label', 'ever-blocks' ),
		'filePath' => 'map-pin.svg',
		'category' => 'places',
	),
	'rocket-launch' => array(
		'label'    => _x( 'Rocket Launch', 'icon label', 'ever-blocks' ),
		'filePath' => 'rocket-launch.svg',
		'category' => 'places',
	),
	'battery-0' => array(
		'label'    => _x( 'Battery 0', 'icon label', 'ever-blocks' ),
		'filePath' => 'battery-0.svg',
		'category' => 'devices',
	),
	'battery-100' => array(
		'label'    => _x( 'Battery 100', 'icon label', 'ever-blocks' ),
		'filePath' => 'battery-100.svg',
		'category' => 'devices',
	),
	'battery-50' => array(
		'label'    => _x( 'Battery 50', 'icon label', 'ever-blocks' ),
		'filePath' => 'battery-50.svg',
		'category' => 'devices',
	),
	'code-bracket' => array(
		'label'    => _x( 'Code Bracket', 'icon label', 'ever-blocks' ),
		'filePath' => 'code-bracket.svg',
		'category' => 'devices',
	),
	'code-bracket-square' => array(
		'label'    => _x( 'Code Bracket Square', 'icon label', 'ever-blocks' ),
		'filePath' => 'code-bracket-square.svg',
		'category' => 'devices',
	),
	'command-line' => array(
		'label'    => _x( 'Command Line', 'icon label', 'ever-blocks' ),
		'filePath' => 'command-line.svg',
		'category' => 'devices',
	),
	'computer-desktop' => array(
		'label'    => _x( 'Computer Desktop', 'icon label', 'ever-blocks' ),
		'filePath' => 'computer-desktop.svg',
		'category' => 'devices',
	),
	'cpu-chip' => array(
		'label'    => _x( 'Cpu Chip', 'icon label', 'ever-blocks' ),
		'filePath' => 'cpu-chip.svg',
		'category' => 'devices',
	),
	'cursor-arrow-rays' => array(
		'label'    => _x( 'Cursor Arrow Rays', 'icon label', 'ever-blocks' ),
		'filePath' => 'cursor-arrow-rays.svg',
		'category' => 'devices',
	),
	'cursor-arrow-ripple' => array(
		'label'    => _x( 'Cursor Arrow Ripple', 'icon label', 'ever-blocks' ),
		'filePath' => 'cursor-arrow-ripple.svg',
		'category' => 'devices',
	),
	'device-phone-mobile' => array(
		'label'    => _x( 'Device Phone Mobile', 'icon label', 'ever-blocks' ),
		'filePath' => 'device-phone-mobile.svg',
		'category' => 'devices',
	),
	'device-tablet' => array(
		'label'    => _x( 'Device Tablet', 'icon label', 'ever-blocks' ),
		'filePath' => 'device-tablet.svg',
		'category' => 'devices',
	),
	'puzzle-piece' => array(
		'label'    => _x( 'Puzzle Piece', 'icon label', 'ever-blocks' ),
		'filePath' => 'puzzle-piece.svg',
		'category' => 'devices',
	),
	'qr-code' => array(
		'label'    => _x( 'Qr Code', 'icon label', 'ever-blocks' ),
		'filePath' => 'qr-code.svg',
		'category' => 'devices',
	),
	'server' => array(
		'label'    => _x( 'Server', 'icon label', 'ever-blocks' ),
		'filePath' => 'server.svg',
		'category' => 'devices',
	),
	'server-stack' => array(
		'label'    => _x( 'Server Stack', 'icon label', 'ever-blocks' ),
		'filePath' => 'server-stack.svg',
		'category' => 'devices',
	),
	'bolt' => array(
		'label'    => _x( 'Bolt', 'icon label', 'ever-blocks' ),
		'filePath' => 'bolt.svg',
		'category' => 'status',
	),
	'bolt-slash' => array(
		'label'    => _x( 'Bolt Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'bolt-slash.svg',
		'category' => 'status',
	),
	'bug-ant' => array(
		'label'    => _x( 'Bug Ant', 'icon label', 'ever-blocks' ),
		'filePath' => 'bug-ant.svg',
		'category' => 'status',
	),
	'check' => array(
		'label'    => _x( 'Check', 'icon label', 'ever-blocks' ),
		'filePath' => 'check.svg',
		'category' => 'status',
	),
	'check-badge' => array(
		'label'    => _x( 'Check Badge', 'icon label', 'ever-blocks' ),
		'filePath' => 'check-badge.svg',
		'category' => 'status',
	),
	'check-circle' => array(
		'label'    => _x( 'Check Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'check-circle.svg',
		'category' => 'status',
	),
	'exclamation-circle' => array(
		'label'    => _x( 'Exclamation Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'exclamation-circle.svg',
		'category' => 'status',
	),
	'exclamation-triangle' => array(
		'label'    => _x( 'Exclamation Triangle', 'icon label', 'ever-blocks' ),
		'filePath' => 'exclamation-triangle.svg',
		'category' => 'status',
	),
	'fire' => array(
		'label'    => _x( 'Fire', 'icon label', 'ever-blocks' ),
		'filePath' => 'fire.svg',
		'category' => 'status',
	),
	'flag' => array(
		'label'    => _x( 'Flag', 'icon label', 'ever-blocks' ),
		'filePath' => 'flag.svg',
		'category' => 'status',
	),
	'heart' => array(
		'label'    => _x( 'Heart', 'icon label', 'ever-blocks' ),
		'filePath' => 'heart.svg',
		'category' => 'status',
	),
	'information-circle' => array(
		'label'    => _x( 'Information Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'information-circle.svg',
		'category' => 'status',
	),
	'lifebuoy' => array(
		'label'    => _x( 'Lifebuoy', 'icon label', 'ever-blocks' ),
		'filePath' => 'lifebuoy.svg',
		'category' => 'status',
	),
	'light-bulb' => array(
		'label'    => _x( 'Light Bulb', 'icon label', 'ever-blocks' ),
		'filePath' => 'light-bulb.svg',
		'category' => 'status',
	),
	'minus' => array(
		'label'    => _x( 'Minus', 'icon label', 'ever-blocks' ),
		'filePath' => 'minus.svg',
		'category' => 'status',
	),
	'minus-circle' => array(
		'label'    => _x( 'Minus Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'minus-circle.svg',
		'category' => 'status',
	),
	'minus-small' => array(
		'label'    => _x( 'Minus Small', 'icon label', 'ever-blocks' ),
		'filePath' => 'minus-small.svg',
		'category' => 'status',
	),
	'no-symbol' => array(
		'label'    => _x( 'No Symbol', 'icon label', 'ever-blocks' ),
		'filePath' => 'no-symbol.svg',
		'category' => 'status',
	),
	'plus' => array(
		'label'    => _x( 'Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'plus.svg',
		'category' => 'status',
	),
	'plus-circle' => array(
		'label'    => _x( 'Plus Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'plus-circle.svg',
		'category' => 'status',
	),
	'plus-small' => array(
		'label'    => _x( 'Plus Small', 'icon label', 'ever-blocks' ),
		'filePath' => 'plus-small.svg',
		'category' => 'status',
	),
	'question-mark-circle' => array(
		'label'    => _x( 'Question Mark Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'question-mark-circle.svg',
		'category' => 'status',
	),
	'radio' => array(
		'label'    => _x( 'Radio', 'icon label', 'ever-blocks' ),
		'filePath' => 'radio.svg',
		'category' => 'status',
	),
	'shield-check' => array(
		'label'    => _x( 'Shield Check', 'icon label', 'ever-blocks' ),
		'filePath' => 'shield-check.svg',
		'category' => 'status',
	),
	'shield-exclamation' => array(
		'label'    => _x( 'Shield Exclamation', 'icon label', 'ever-blocks' ),
		'filePath' => 'shield-exclamation.svg',
		'category' => 'status',
	),
	'slash' => array(
		'label'    => _x( 'Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'slash.svg',
		'category' => 'status',
	),
	'sparkles' => array(
		'label'    => _x( 'Sparkles', 'icon label', 'ever-blocks' ),
		'filePath' => 'sparkles.svg',
		'category' => 'status',
	),
	'star' => array(
		'label'    => _x( 'Star', 'icon label', 'ever-blocks' ),
		'filePath' => 'star.svg',
		'category' => 'status',
	),
	'trophy' => array(
		'label'    => _x( 'Trophy', 'icon label', 'ever-blocks' ),
		'filePath' => 'trophy.svg',
		'category' => 'status',
	),
	'x-circle' => array(
		'label'    => _x( 'X Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'x-circle.svg',
		'category' => 'status',
	),
	'x-mark' => array(
		'label'    => _x( 'X Mark', 'icon label', 'ever-blocks' ),
		'filePath' => 'x-mark.svg',
		'category' => 'status',
	),
	'eye' => array(
		'label'    => _x( 'Eye', 'icon label', 'ever-blocks' ),
		'filePath' => 'eye.svg',
		'category' => 'security',
	),
	'eye-slash' => array(
		'label'    => _x( 'Eye Slash', 'icon label', 'ever-blocks' ),
		'filePath' => 'eye-slash.svg',
		'category' => 'security',
	),
	'finger-print' => array(
		'label'    => _x( 'Finger Print', 'icon label', 'ever-blocks' ),
		'filePath' => 'finger-print.svg',
		'category' => 'security',
	),
	'key' => array(
		'label'    => _x( 'Key', 'icon label', 'ever-blocks' ),
		'filePath' => 'key.svg',
		'category' => 'security',
	),
	'lock-closed' => array(
		'label'    => _x( 'Lock Closed', 'icon label', 'ever-blocks' ),
		'filePath' => 'lock-closed.svg',
		'category' => 'security',
	),
	'lock-open' => array(
		'label'    => _x( 'Lock Open', 'icon label', 'ever-blocks' ),
		'filePath' => 'lock-open.svg',
		'category' => 'security',
	),
	'power' => array(
		'label'    => _x( 'Power', 'icon label', 'ever-blocks' ),
		'filePath' => 'power.svg',
		'category' => 'security',
	),
	'adjustments-horizontal' => array(
		'label'    => _x( 'Adjustments Horizontal', 'icon label', 'ever-blocks' ),
		'filePath' => 'adjustments-horizontal.svg',
		'category' => 'tools',
	),
	'adjustments-vertical' => array(
		'label'    => _x( 'Adjustments Vertical', 'icon label', 'ever-blocks' ),
		'filePath' => 'adjustments-vertical.svg',
		'category' => 'tools',
	),
	'backspace' => array(
		'label'    => _x( 'Backspace', 'icon label', 'ever-blocks' ),
		'filePath' => 'backspace.svg',
		'category' => 'tools',
	),
	'beaker' => array(
		'label'    => _x( 'Beaker', 'icon label', 'ever-blocks' ),
		'filePath' => 'beaker.svg',
		'category' => 'tools',
	),
	'cake' => array(
		'label'    => _x( 'Cake', 'icon label', 'ever-blocks' ),
		'filePath' => 'cake.svg',
		'category' => 'tools',
	),
	'cloud' => array(
		'label'    => _x( 'Cloud', 'icon label', 'ever-blocks' ),
		'filePath' => 'cloud.svg',
		'category' => 'tools',
	),
	'cloud-arrow-down' => array(
		'label'    => _x( 'Cloud Arrow Down', 'icon label', 'ever-blocks' ),
		'filePath' => 'cloud-arrow-down.svg',
		'category' => 'tools',
	),
	'cloud-arrow-up' => array(
		'label'    => _x( 'Cloud Arrow Up', 'icon label', 'ever-blocks' ),
		'filePath' => 'cloud-arrow-up.svg',
		'category' => 'tools',
	),
	'cog' => array(
		'label'    => _x( 'Cog', 'icon label', 'ever-blocks' ),
		'filePath' => 'cog.svg',
		'category' => 'tools',
	),
	'cog-6-tooth' => array(
		'label'    => _x( 'Cog 6 Tooth', 'icon label', 'ever-blocks' ),
		'filePath' => 'cog-6-tooth.svg',
		'category' => 'tools',
	),
	'cog-8-tooth' => array(
		'label'    => _x( 'Cog 8 Tooth', 'icon label', 'ever-blocks' ),
		'filePath' => 'cog-8-tooth.svg',
		'category' => 'tools',
	),
	'ellipsis-horizontal' => array(
		'label'    => _x( 'Ellipsis Horizontal', 'icon label', 'ever-blocks' ),
		'filePath' => 'ellipsis-horizontal.svg',
		'category' => 'tools',
	),
	'ellipsis-horizontal-circle' => array(
		'label'    => _x( 'Ellipsis Horizontal Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'ellipsis-horizontal-circle.svg',
		'category' => 'tools',
	),
	'ellipsis-vertical' => array(
		'label'    => _x( 'Ellipsis Vertical', 'icon label', 'ever-blocks' ),
		'filePath' => 'ellipsis-vertical.svg',
		'category' => 'tools',
	),
	'funnel' => array(
		'label'    => _x( 'Funnel', 'icon label', 'ever-blocks' ),
		'filePath' => 'funnel.svg',
		'category' => 'tools',
	),
	'magnifying-glass' => array(
		'label'    => _x( 'Magnifying Glass', 'icon label', 'ever-blocks' ),
		'filePath' => 'magnifying-glass.svg',
		'category' => 'tools',
	),
	'magnifying-glass-circle' => array(
		'label'    => _x( 'Magnifying Glass Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'magnifying-glass-circle.svg',
		'category' => 'tools',
	),
	'magnifying-glass-minus' => array(
		'label'    => _x( 'Magnifying Glass Minus', 'icon label', 'ever-blocks' ),
		'filePath' => 'magnifying-glass-minus.svg',
		'category' => 'tools',
	),
	'magnifying-glass-plus' => array(
		'label'    => _x( 'Magnifying Glass Plus', 'icon label', 'ever-blocks' ),
		'filePath' => 'magnifying-glass-plus.svg',
		'category' => 'tools',
	),
	'moon' => array(
		'label'    => _x( 'Moon', 'icon label', 'ever-blocks' ),
		'filePath' => 'moon.svg',
		'category' => 'tools',
	),
	'sun' => array(
		'label'    => _x( 'Sun', 'icon label', 'ever-blocks' ),
		'filePath' => 'sun.svg',
		'category' => 'tools',
	),
	'trash' => array(
		'label'    => _x( 'Trash', 'icon label', 'ever-blocks' ),
		'filePath' => 'trash.svg',
		'category' => 'tools',
	),
	'viewfinder-circle' => array(
		'label'    => _x( 'Viewfinder Circle', 'icon label', 'ever-blocks' ),
		'filePath' => 'viewfinder-circle.svg',
		'category' => 'tools',
	),
	'wrench' => array(
		'label'    => _x( 'Wrench', 'icon label', 'ever-blocks' ),
		'filePath' => 'wrench.svg',
		'category' => 'tools',
	),
	'wrench-screwdriver' => array(
		'label'    => _x( 'Wrench Screwdriver', 'icon label', 'ever-blocks' ),
		'filePath' => 'wrench-screwdriver.svg',
		'category' => 'tools',
	),
);
